symfony/src/Entity/ExchangeRate.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ExchangeRateRepository")
 */
class ExchangeRate
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $short_name;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $rate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getShortName(): ?string
    {
        return $this->short_name;
    }

    public function setShortName(string $short_name): self
    {
        $this->short_name = $short_name;

        return $this;
    }

    public function getRate(): ?string
    {
        return $this->rate;
    }

    public function setRate(?string $rate): self
    {
        $this->rate = $rate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

symfony/src/Controller/ExchangeratesController.php
<?php


namespace App\Controller;


use App\Repository\ExchangeRateRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ExchangeratesController extends AbstractController
{

    /**
     * @Route("/", name="app_home")
     */

     public function index(ExchangeRateRepository $repository, PaginatorInterface $paginator, Request $request){
        $query = $repository->findLatestRates();
        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            20 /*limit per page*/
        );

        //$todayDate = new \DateTime();
        $latestDate = $repository->findLatestDate();

        return $this->render('exchangerate/index.html.twig',[
            'pagination' => $pagination,
            'longNames' => $this->getLongNames(),
            'latestDate' => $latestDate ? $latestDate[0]['1'] : ''
        ]);
    }

    /**
     * @Route("/rate/{id}")
     */
    public function show($id, ExchangeRateRepository $repository){

        $currAndRate = $repository->find($id);
        if($currAndRate){
            $histRates = $repository->findHistoricalRatesByRate($currAndRate->getShortName(), $currAndRate->getDate());
        }else{
            return $this->redirectToRoute('app_home');
        }

        return $this->render('exchangerate/show.html.twig',[
            'rate' => 'Showing the rate with id:'.$id,
            'longNames' => $this->getLongNames(),
            'currAndRate' => $currAndRate,
            'histRates' => $histRates
        ]);
    }

    public function getLongNames(){
        return array(
            "AUD" => "Australia, Dollars",
            "BGN" => "Bulgaria, Leva",
            "BRL" => "Brazil, Real",
            "CAD" => "Canada, Dollars",
            "CHF" => "Switzerland, Francs",
            "CNY" => "China, Yuan Renminbi",
            "CZK" => "Czech Republic, Koruny",
            "DKK" => "Denmark, Kroner",
            "GBP" => "United Kingdom, Pounds",
            "HKD" => "Hong Kong, Dollars",
            "HRK" => "Croatia, Kuna",
            "HUF" => "Hungary, Forint",
            "IDR" => "Indonesia, Rupiah",
            "ILS" => "Israel, New Shekels",
            "INR" => "India, Rupees",
            "ISK" => "Iceland, Kronur",
            "JPY" => "Japan, Yen",
            "KRW" => "Korea (South), Won",
            "MXN" => "Mexico, Peso",
            "MYR" => "Malaysia, Ringgit",
            "NOK" => "Norway, Krone",
            "NZD" => "New Zealand, Dollars",
            "PHP" => "Philippines, Peso",
            "PLN" => "Poland, Zlotych",
            "RON" => "Romania, New Lei",
            "RUB" => "Russia, Rubles",
            "SEK" => "Sweden, Kronor",
            "SGD" => "Singapore, Dollars",
            "THB" => "Thailand, Baht",
            "TRY" => "Turkey, Lira",
            "USD" => "United States of America, Dollars",
            "ZAR" => "South Africa, Rand"
        );
    }

}

symfony/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Spartan&display=swap">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
            <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

symfony/templates/exchangerate/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container">
        <div class="row">

            {% if pagination|length > 0 %}

            <div class="col-12 text-center">
                <h2 class="my-4">Latest exchange rates for date: {{ latestDate }}</h2>
                <p>Total rates in list ({{ pagination.getTotalItemCount }})</p>

                <table class="table table-hover">
                    <thead>
                    <tr class="table-info">
                        <th scope="col">Date</th>
                        <th scope="col">Currency</th>
                        <th scope="col">Short name</th>
                        <th scope="col">Value</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for rate in pagination %}
                    <tr>
                        <td scope="row">{{ rate.date|date("Y-m-d") }}</td>
                        <td class="text-left"><a title="Follow the link for rate details and historical rate values" href="{{ path('app_exchangerates_show', {id:rate.id}) }}">
                                {% for k, v in longNames|filter((v,k) => k == rate.shortName) -%}
                                    {{ v }}
                                {% endfor %}
                            </a></td>
                        <td>{{rate.shortName}}</td>
                        <td class="text-right">{{rate.rate}}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {{ knp_pagination_render(pagination) }}
            </div>

            {% else %}

            <div class="col-12 text-center">
                <h2 class="my-4">Latest exchange rates</h2>
                <div class="alert alert-danger">
                    Database seems to be empty!
                </div>
                <p>To populate the database go to your Docker php container and execute following command:</p>
                <div class="alert alert-light border border-info" role="alert">
                    $ php bin/console load-rates
                </div>
                <p>Then refresh the page. </p>
            </div>

            {% endif %}

        </div>
    </div>

{% endblock %}

symfony/templates/exchangerate/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="my-4">Exchange rate for selected currency and historical values</h2>
                <p>Latest exchange rate details for selected currency</p>

                <div class="row">
                    <div class="col"></div>
                    <div class="col-3"></div>
                    <div class="col-3 alert alert-info">
                        {{ currAndRate.date|date("Y-m-d") }}
                    </div>
                    <div class="col-3"></div>
                    <div class="col"></div>
                </div>
                <div class="row text-center">
                    <div class="col">

                    </div>
                    <div class="col-3 alert alert-warning ">
                        {% for k, v in longNames|filter((v,k) => k == currAndRate.shortName) -%}
                            {{ v }}
                        {% endfor %}
                    </div>
                    <div class="col-3 alert alert-warning mx-2">
                        {{currAndRate.shortName}}
                    </div>
                    <div class="col-3 alert alert-warning text-info font-weight-bold">
                        {{currAndRate.rate}}
                    </div>
                    <div class="col">

                    </div>
                </div>

            </div>
        </div>

    <div class="row">
        <div class="col-12 text-center mt-4">
            <p>Historical exchange rate values</p>

            <table class="table table-hover">
                <thead>
                    <tr class="table-info">
                        <th scope="col">Date</th>
                        <th scope="col">Currency</th>
                        <th scope="col">Short name</th>
                        <th scope="col">Value</th>
                    </tr>
                </thead>
                <tbody>

                {% for rate in histRates %}
                    <tr>
                        <td scope="row">{{ rate.date|date("Y-m-d") }}</td>
                        <td class="text-left">
                                {% for k, v in longNames|filter((v,k) => k == rate.shortName) -%}
                                    {{ v }}
                                {% endfor %}
                            </td>
                        <td>{{rate.shortName}}</td>
                        <td class="text-right">{{rate.rate}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
        <p>
            <a class="btn btn btn-outline-info" href="{{ path('app_home') }}" role="button">Back to list</a>
        </p>
    </div>



{% endblock %}